sudo: required
services:
      - docker
before_install:
      - docker build -t temp -f Dockerfile.dev .

script:
        - docker run -it temp npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-873473197052"
  bucket_path: "docker-react"
  on:
   branch: master 
  access_key_id: $AWS_A_KEY
  secret_access_key:
   secure: "$AWS_S_KEY"
